// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'ecfd475549100cfd8f7a7908c55545fa152e8d1b9d87c200aacc23a64413a8c5'>;
export type ExecutionHash =
  ExecutionHashBase<'7af7d60f35bfa7881c65f72e48635a91119807cf92467c668deab1f453e70973'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Categoria: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly ItemPedido: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly pedidoId: CodecTypes['pg/uuid@1']['output'];
      readonly produtoId: CodecTypes['pg/uuid@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['output'];
      readonly observacoes: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'PENDING' | 'PREPARING' | 'READY' | 'DELIVERED' | 'CANCELED';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly LogAuditoria: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly usuarioId: CodecTypes['pg/uuid@1']['output'];
      readonly acao: CodecTypes['pg/text@1']['output'];
      readonly entidade: CodecTypes['pg/text@1']['output'];
      readonly entidadeId: CodecTypes['pg/text@1']['output'] | null;
      readonly metadados: CodecTypes['pg/json@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Mesa: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly numero: CodecTypes['pg/int4@1']['output'];
      readonly status: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Pagamento: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly pedidoId: CodecTypes['pg/uuid@1']['output'];
      readonly forma: 'CASH' | 'CREDIT' | 'DEBIT' | 'PIX';
      readonly valor: CodecTypes['pg/numeric@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Pedido: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly mesaId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly usuarioId: CodecTypes['pg/uuid@1']['output'];
      readonly status: 'OPEN' | 'IN_KITCHEN' | 'READY' | 'DELIVERED' | 'CANCELED' | 'CLOSED';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    };
    readonly Perfil: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: 'ADMIN' | 'MANAGER' | 'CHEF' | 'WAITER' | 'CASHIER';
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly PerfilPermissao: {
      readonly perfilId: CodecTypes['pg/uuid@1']['output'];
      readonly permissaoId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Permissao: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Produto: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly preco: CodecTypes['pg/numeric@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly categoriaId: CodecTypes['pg/uuid@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly pin: CodecTypes['pg/text@1']['output'];
      readonly perfilId: CodecTypes['pg/uuid@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Categoria: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly ItemPedido: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly pedidoId: CodecTypes['pg/uuid@1']['input'];
      readonly produtoId: CodecTypes['pg/uuid@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['input'];
      readonly observacoes: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'PENDING' | 'PREPARING' | 'READY' | 'DELIVERED' | 'CANCELED';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly LogAuditoria: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly usuarioId: CodecTypes['pg/uuid@1']['input'];
      readonly acao: CodecTypes['pg/text@1']['input'];
      readonly entidade: CodecTypes['pg/text@1']['input'];
      readonly entidadeId: CodecTypes['pg/text@1']['input'] | null;
      readonly metadados: CodecTypes['pg/json@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Mesa: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly numero: CodecTypes['pg/int4@1']['input'];
      readonly status: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Pagamento: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly pedidoId: CodecTypes['pg/uuid@1']['input'];
      readonly forma: 'CASH' | 'CREDIT' | 'DEBIT' | 'PIX';
      readonly valor: CodecTypes['pg/numeric@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Pedido: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly mesaId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly usuarioId: CodecTypes['pg/uuid@1']['input'];
      readonly status: 'OPEN' | 'IN_KITCHEN' | 'READY' | 'DELIVERED' | 'CANCELED' | 'CLOSED';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
    };
    readonly Perfil: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: 'ADMIN' | 'MANAGER' | 'CHEF' | 'WAITER' | 'CASHIER';
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly PerfilPermissao: {
      readonly perfilId: CodecTypes['pg/uuid@1']['input'];
      readonly permissaoId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Permissao: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Produto: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly preco: CodecTypes['pg/numeric@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly categoriaId: CodecTypes['pg/uuid@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly pin: CodecTypes['pg/text@1']['input'];
      readonly perfilId: CodecTypes['pg/uuid@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categorias: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly itens_pedido: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly observacoes: CodecTypes['pg/text@1']['output'] | null;
      readonly pedidoId: CodecTypes['pg/uuid@1']['output'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['output'];
      readonly produtoId: CodecTypes['pg/uuid@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly status: 'PENDING' | 'PREPARING' | 'READY' | 'DELIVERED' | 'CANCELED';
    };
    readonly logs_auditoria: {
      readonly acao: CodecTypes['pg/text@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly entidade: CodecTypes['pg/text@1']['output'];
      readonly entidadeId: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly metadados: CodecTypes['pg/json@1']['output'] | null;
      readonly usuarioId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly mesas: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly numero: CodecTypes['pg/int4@1']['output'];
      readonly status: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED';
    };
    readonly pagamentos: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly forma: 'CASH' | 'CREDIT' | 'DEBIT' | 'PIX';
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly pedidoId: CodecTypes['pg/uuid@1']['output'];
      readonly valor: CodecTypes['pg/numeric@1']['output'];
    };
    readonly pedidos: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly mesaId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly status: 'OPEN' | 'IN_KITCHEN' | 'READY' | 'DELIVERED' | 'CANCELED' | 'CLOSED';
      readonly usuarioId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly perfil_permissoes: {
      readonly perfilId: CodecTypes['pg/uuid@1']['output'];
      readonly permissaoId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly perfis: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: 'ADMIN' | 'MANAGER' | 'CHEF' | 'WAITER' | 'CASHIER';
    };
    readonly permissoes: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly produtos: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly categoriaId: CodecTypes['pg/uuid@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly preco: CodecTypes['pg/numeric@1']['output'];
    };
    readonly usuarios: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly perfilId: CodecTypes['pg/uuid@1']['output'];
      readonly pin: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categorias: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly itens_pedido: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly observacoes: CodecTypes['pg/text@1']['input'] | null;
      readonly pedidoId: CodecTypes['pg/uuid@1']['input'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['input'];
      readonly produtoId: CodecTypes['pg/uuid@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly status: 'PENDING' | 'PREPARING' | 'READY' | 'DELIVERED' | 'CANCELED';
    };
    readonly logs_auditoria: {
      readonly acao: CodecTypes['pg/text@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly entidade: CodecTypes['pg/text@1']['input'];
      readonly entidadeId: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly metadados: CodecTypes['pg/json@1']['input'] | null;
      readonly usuarioId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly mesas: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly numero: CodecTypes['pg/int4@1']['input'];
      readonly status: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED';
    };
    readonly pagamentos: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly forma: 'CASH' | 'CREDIT' | 'DEBIT' | 'PIX';
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly pedidoId: CodecTypes['pg/uuid@1']['input'];
      readonly valor: CodecTypes['pg/numeric@1']['input'];
    };
    readonly pedidos: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly mesaId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly status: 'OPEN' | 'IN_KITCHEN' | 'READY' | 'DELIVERED' | 'CANCELED' | 'CLOSED';
      readonly usuarioId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly perfil_permissoes: {
      readonly perfilId: CodecTypes['pg/uuid@1']['input'];
      readonly permissaoId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly perfis: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: 'ADMIN' | 'MANAGER' | 'CHEF' | 'WAITER' | 'CASHIER';
    };
    readonly permissoes: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly produtos: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly categoriaId: CodecTypes['pg/uuid@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly preco: CodecTypes['pg/numeric@1']['input'];
    };
    readonly usuarios: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly perfilId: CodecTypes['pg/uuid@1']['input'];
      readonly pin: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categorias: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nome'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly itens_pedido: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly pedidoId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly produtoId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly precoUnitario: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly observacoes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'itens_pedido_pedidoId_idx_4742647d';
                  readonly prefix: 'itens_pedido_pedidoId_idx';
                  readonly columns: readonly ['pedidoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'itens_pedido_produtoId_idx_eb62fdb9';
                  readonly prefix: 'itens_pedido_produtoId_idx';
                  readonly columns: readonly ['produtoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'itens_pedido';
                    readonly columns: readonly ['pedidoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'itens_pedido';
                    readonly columns: readonly ['produtoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'produtos';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly logs_auditoria: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly usuarioId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly acao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly entidade: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly entidadeId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly metadados: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'logs_auditoria_usuarioId_idx_5f01c7d6';
                  readonly prefix: 'logs_auditoria_usuarioId_idx';
                  readonly columns: readonly ['usuarioId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'logs_auditoria_entidade_entidadeId_idx_8ba55fde';
                  readonly prefix: 'logs_auditoria_entidade_entidadeId_idx';
                  readonly columns: readonly ['entidade', 'entidadeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'logs_auditoria';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly mesas: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly numero: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'AVAILABLE'>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['numero'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly pagamentos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly pedidoId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly forma: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly valor: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'pagamentos_pedidoId_idx_4742647d';
                  readonly prefix: 'pagamentos_pedidoId_idx';
                  readonly columns: readonly ['pedidoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pagamentos';
                    readonly columns: readonly ['pedidoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly pedidos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly mesaId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
                readonly usuarioId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'OPEN'>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly fechadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'pedidos_mesaId_idx_81c645f6';
                  readonly prefix: 'pedidos_mesaId_idx';
                  readonly columns: readonly ['mesaId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pedidos_usuarioId_idx_5f01c7d6';
                  readonly prefix: 'pedidos_usuarioId_idx';
                  readonly columns: readonly ['usuarioId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pedidos_status_idx_e98638ab';
                  readonly prefix: 'pedidos_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['mesaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'mesas';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pedidos';
                    readonly columns: readonly ['usuarioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly perfil_permissoes: {
              columns: {
                readonly perfilId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly permissaoId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['perfilId', 'permissaoId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'perfil_permissoes_perfilId_idx_18f1fe5e';
                  readonly prefix: 'perfil_permissoes_perfilId_idx';
                  readonly columns: readonly ['perfilId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'perfil_permissoes_permissaoId_idx_32efd59e';
                  readonly prefix: 'perfil_permissoes_permissaoId_idx';
                  readonly columns: readonly ['permissaoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'perfil_permissoes';
                    readonly columns: readonly ['perfilId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'perfis';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'perfil_permissoes';
                    readonly columns: readonly ['permissaoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'permissoes';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly perfis: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nome'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly permissoes: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nome'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly produtos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly preco: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly categoriaId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'produtos_categoriaId_idx_63b46427';
                  readonly prefix: 'produtos_categoriaId_idx';
                  readonly columns: readonly ['categoriaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'produtos';
                    readonly columns: readonly ['categoriaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categorias';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly usuarios: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pin: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly perfilId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'usuarios_perfilId_idx_18f1fe5e';
                  readonly prefix: 'usuarios_perfilId_idx';
                  readonly columns: readonly ['perfilId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['perfilId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'perfis';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly OrderItemStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'PREPARING', 'READY', 'DELIVERED', 'CANCELED'];
            };
            readonly OrderStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'OPEN',
                'IN_KITCHEN',
                'READY',
                'DELIVERED',
                'CANCELED',
                'CLOSED',
              ];
            };
            readonly PaymentMethod: {
              readonly kind: 'valueSet';
              readonly values: readonly ['CASH', 'CREDIT', 'DEBIT', 'PIX'];
            };
            readonly RoleName: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'MANAGER', 'CHEF', 'WAITER', 'CASHIER'];
            };
            readonly TableStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['AVAILABLE', 'OCCUPIED', 'RESERVED'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly usuarios: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
    readonly perfis: { readonly namespace: 'public' & NamespaceId; readonly model: 'Perfil' };
    readonly permissoes: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Permissao';
    };
    readonly perfil_permissoes: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PerfilPermissao';
    };
    readonly logs_auditoria: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'LogAuditoria';
    };
    readonly categorias: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Categoria';
    };
    readonly produtos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Produto' };
    readonly mesas: { readonly namespace: 'public' & NamespaceId; readonly model: 'Mesa' };
    readonly pedidos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pedido' };
    readonly itens_pedido: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ItemPedido';
    };
    readonly pagamentos: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Pagamento';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Categoria: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly produtos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoriaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categorias';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly ativo: { readonly column: 'ativo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
          readonly ItemPedido: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly pedidoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly produtoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly precoUnitario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly observacoes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly pedido: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pedido';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['pedidoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly produto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['produtoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'itens_pedido';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly pedidoId: { readonly column: 'pedidoId' };
                readonly produtoId: { readonly column: 'produtoId' };
                readonly quantidade: { readonly column: 'quantidade' };
                readonly precoUnitario: { readonly column: 'precoUnitario' };
                readonly observacoes: { readonly column: 'observacoes' };
                readonly status: { readonly column: 'status' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
          readonly LogAuditoria: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly usuarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly acao: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly entidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly entidadeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metadados: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'logs_auditoria';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly acao: { readonly column: 'acao' };
                readonly entidade: { readonly column: 'entidade' };
                readonly entidadeId: { readonly column: 'entidadeId' };
                readonly metadados: { readonly column: 'metadados' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Mesa: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly numero: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly pedidos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pedido';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['mesaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'mesas';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly numero: { readonly column: 'numero' };
                readonly status: { readonly column: 'status' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
          readonly Pagamento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly pedidoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly forma: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly valor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly pedido: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pedido';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['pedidoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pagamentos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly pedidoId: { readonly column: 'pedidoId' };
                readonly forma: { readonly column: 'forma' };
                readonly valor: { readonly column: 'valor' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Pedido: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly mesaId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly usuarioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fechadoEm: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly itens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemPedido';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['pedidoId'];
                };
              };
              readonly mesa: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Mesa' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['mesaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly pagamentos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pagamento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['pedidoId'];
                };
              };
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pedidos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly mesaId: { readonly column: 'mesaId' };
                readonly usuarioId: { readonly column: 'usuarioId' };
                readonly status: { readonly column: 'status' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
                readonly fechadoEm: { readonly column: 'fechadoEm' };
              };
            };
          };
          readonly Perfil: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly permissoes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PerfilPermissao';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['perfilId'];
                };
              };
              readonly usuarios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['perfilId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'perfis';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly descricao: { readonly column: 'descricao' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
          readonly PerfilPermissao: {
            readonly fields: {
              readonly perfilId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly permissaoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly perfil: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Perfil';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['perfilId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly permissao: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Permissao';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['permissaoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'perfil_permissoes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly perfilId: { readonly column: 'perfilId' };
                readonly permissaoId: { readonly column: 'permissaoId' };
              };
            };
          };
          readonly Permissao: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly perfis: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PerfilPermissao';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['permissaoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'permissoes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly descricao: { readonly column: 'descricao' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Produto: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly preco: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly categoriaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly categoria: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Categoria';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['categoriaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly itensPedido: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemPedido';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['produtoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'produtos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly descricao: { readonly column: 'descricao' };
                readonly preco: { readonly column: 'preco' };
                readonly ativo: { readonly column: 'ativo' };
                readonly categoriaId: { readonly column: 'categoriaId' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pin: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly perfilId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly logsAuditoria: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LogAuditoria';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly pedidos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pedido';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly perfil: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Perfil';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['perfilId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuarios';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly pin: { readonly column: 'pin' };
                readonly perfilId: { readonly column: 'perfilId' };
                readonly ativo: { readonly column: 'ativo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
        };
        readonly enum: {
          readonly RoleName: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
              { readonly name: 'MANAGER'; readonly value: 'MANAGER' },
              { readonly name: 'CHEF'; readonly value: 'CHEF' },
              { readonly name: 'WAITER'; readonly value: 'WAITER' },
              { readonly name: 'CASHIER'; readonly value: 'CASHIER' },
            ];
          };
          readonly OrderStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'OPEN'; readonly value: 'OPEN' },
              { readonly name: 'IN_KITCHEN'; readonly value: 'IN_KITCHEN' },
              { readonly name: 'READY'; readonly value: 'READY' },
              { readonly name: 'DELIVERED'; readonly value: 'DELIVERED' },
              { readonly name: 'CANCELED'; readonly value: 'CANCELED' },
              { readonly name: 'CLOSED'; readonly value: 'CLOSED' },
            ];
          };
          readonly OrderItemStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'PREPARING'; readonly value: 'PREPARING' },
              { readonly name: 'READY'; readonly value: 'READY' },
              { readonly name: 'DELIVERED'; readonly value: 'DELIVERED' },
              { readonly name: 'CANCELED'; readonly value: 'CANCELED' },
            ];
          };
          readonly PaymentMethod: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'CASH'; readonly value: 'CASH' },
              { readonly name: 'CREDIT'; readonly value: 'CREDIT' },
              { readonly name: 'DEBIT'; readonly value: 'DEBIT' },
              { readonly name: 'PIX'; readonly value: 'PIX' },
            ];
          };
          readonly TableStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'AVAILABLE'; readonly value: 'AVAILABLE' },
              { readonly name: 'OCCUPIED'; readonly value: 'OCCUPIED' },
              { readonly name: 'RESERVED'; readonly value: 'RESERVED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'categorias';
            readonly column: 'atualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'categorias';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'itens_pedido';
            readonly column: 'atualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'itens_pedido';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'logs_auditoria';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'mesas';
            readonly column: 'atualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'mesas';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pagamentos';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pedidos';
            readonly column: 'atualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'pedidos';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'perfis';
            readonly column: 'atualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'perfis';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'permissoes';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'produtos';
            readonly column: 'atualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'produtos';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'usuarios';
            readonly column: 'atualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'usuarios';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
